name: Stefano Pelloni
favicon: null
layout_spectrum: 0.11423998465761542
typography_spectrum: 0.44590694457292557
title: Portfolio Personale · Curriculum Online
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#ff4342'
    - '#090909'
    - '#828282'
    - '#bababa'
  brandStrength: 0.5
  lightness: 0.0625
  saturation: 0.5
  rhythmicContrast: 0.6424203305505216
purpose: []
